workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
      flutter: stable
    scripts:
      - name: Create Android scaffolding
        script: |
          # Android altyapısını eksiksiz sıfırdan oluştur
          flutter create . --platforms=android --org com.cryptoradar
      - name: Clean and Get packages
        script: |
          flutter clean
          flutter pub get
      - name: Build Android APK
        script: |
          # APK derlemesi
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
